packages:
  - apps/*
  - packages/*
  - configs/*

catalog:
  '@trpc/client': ^11.8.0
  '@trpc/server': ^11.8.0
  '@types/node': 25.0.3
  better-auth: 1.4.7
  eslint: 9.39.2
  prettier: 3.7.4
  prettier-plugin-tailwindcss: ^0.7.2
  tailwindcss: 4.1.18
  typescript: 5.9.3
  zod: 4.2.1

ignoredBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - prisma

linkWorkspacePackages: true
