packages:
  - apps/*
  - packages/*
  - configs/*

catalog:
  '@trpc/client': ^11.8.1
  '@trpc/server': ^11.8.1
  '@types/node': ^25.0.8
  '@types/react': ^19.2.8
  '@types/react-dom': ^19.2.3
  better-auth: ^1.4.12
  eslint: ^9.39.2
  prettier: ^3.7.4
  prettier-plugin-tailwindcss: ^0.7.2
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  zod: ^4.3.5

ignoredBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - prisma

linkWorkspacePackages: true
